version: '2'

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml

  blackbox_exporter:
    image: prom/blackbox-exporter
    container_name: blackbox_exporter
    ports:
      - 9115:9115
    volumes:
      - ./blackbox:/etc/blackbox
    command:
      - --config.file=/etc/blackbox/blackbox.yml

  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    # if you are running as root then set user to 0
    # else find the right id with the id -u command
    user: '0'
    ports:
      - 3000:3000
    volumes:
      - ~/grafana_data:/var/lib/grafana

